services:
  crawl4ai:
    image: unclecode/crawl4ai:all-amd64
    container_name: crawl4ai
    restart: unless-stopped
    ports:
      - "11235:11235"
    environment:
      - CRAWL4AI_API_TOKEN=${CRAWL4AI_API_TOKEN:-}
      - MAX_CONCRRENT_TASKS=${MAX_CONCRRENT_TASKS:-5}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - aff-network
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.routers.crawl4ai.rule=Host(`c4i.theintelliagent.com`)
    #   - traefik.http.routers.crawl4ai.entrypoints=websecure
    #   - traefik.http.routers.crawl4ai.tls=true
    #   - traefik.http.routers.crawl4ai.tls.certresolver=myresolver
    #   - traefik.http.services.crawl4ai.loadbalancer.server.port=11235

networks:
  aff-network:
    external: true