services:
  crawl4ai:
    image: unclecode/crawl4ai:all
    container_name: crawl4ai
    restart: unless-stopped
    ports:
      - "11235:11235"
    environment:
      - CRAWL4AI_API_TOKEN=${CRAWL4AI_API_TOKEN:-}
      - MAX_CONCRRENT_TASKS=${MAX_CONCRRENT_TASKS:-5}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - aff_infra_proxy-network
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G

networks:
  aff_infra_proxy-network:
    external: true